services:
  transcendence_db:
    build:
      context: ./postgreSQL
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    networks:
      custom_network:
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  web:
    build:
      context: ./django
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      custom_network:
    env_file:
      - .env
    environment:
      HOST_IP: 10.0.2.15
      DJANGO_SETTINGS_MODULE: transcendence.settings
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
    depends_on:
      - transcendence_db
    command: ["sh", "-c", "./wait_for_db.sh && ./cert_gen.sh && python3 manage.py migrate && daphne -b 0.0.0.0 -p 8000 transcendence.asgi:application"]

  redis:
    image: "redis:alpine"
    ports:
      - "6370:6379"
    networks:
      custom_network:

networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.2.0/24
