services:
  transcendence_db:
    build:
      context: ./postgreSQL
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    networks:
      custom_network:
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  web:
    build:
      context: ./django
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      custom_network:
    environment:
      DJANGO_SETTINGS_MODULE: transcendence.settings
    depends_on:
      - transcendence_db
    command: ["sh", "-c", "python3 manage.py migrate && daphne -b 0.0.0.0 -p 8000 transcendence.asgi:application"]

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "8443:443"
    networks:
      custom_network:
    depends_on:
      - transcendence_db

  redis:
    image: "redis:alpine"
    ports:
      - "6370:6379"
    networks:
      custom_network:

networks:
  custom_network:
    driver: bridge
